logs_bucket = "capstone-logs"
lambda_function_local_path = "../src/main.py"
docker_image_local_path = "Dockerfile"
ecr_repo_name = "capstone_ecr"
lambda_function_name = "capstone_lambda"
endpoint_name = "capstone_endpoint"
