[tool.pylint.messages_control]

disable = [
    "no-name-in-module",
    "missing-module-docstring",
    "missing-class-docstring",
    "ungrouped-imports"
]

[tool.isort]
profile = "black"


[tool.pytest.ini_options]
filterwarnings = [
    "ignore::FutureWarning",
    "ignore::DeprecationWarning"
]
